# Site settings
title: Ace Motanya
email: acmotanya@gmail.com
url: acmotanya.com
description: "Ace Motanya - Software Dev"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#2174b3'

# Footer settings
footer: Motanya

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/aceboom
  - title: facebook
    url: https://www.facebook.com/AceBoogie
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
